---
{{- $tag := .Values.image.tag | default .Chart.AppVersion -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: po-stamp-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: po-stamp
spec:
  replicas: {{ .Values.stamp.replicaCount }}
  selector:
    matchLabels:
      app: po-stamp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: po-stamp
    spec:
      serviceAccountName: stamp-migration-waiter
      initContainers:
        - name: wait-for-migration
          image: groundnuty/k8s-wait-for:v2.0 # TODO verify this image
          args:
            - "job"
            - "po-stamp-migrate-job-{{ .Values.image.tag | default .Chart.AppVersion | replace "." "-" }}"
      containers:
        - name: po-stamp
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          args:
            - "--serve"
          env:
            {{- include "common.database.config" $ | nindent 12 }}

            - name: RestApiOptions__PathBase
              value: {{ .Values.config.pathBase }}
          {{- if eq .Values.messageBroker.type "inMemory" }}
            - name: MessageBroker__Type
              value: InMemory
          {{- else if eq .Values.messageBroker.type "rabbitmq" }}
            - name: MessageBroker__Type
              value: RabbitMq
            - name: MessageBroker__RabbitMQ__Host
              value: {{ required "A valid messageBroker rabbitmq host is required!" .Values.messageBroker.rabbitmq.host }}
            - name: MessageBroker__RabbitMQ__Port
              value: {{ required "A valid messageBroker rabbitmq port is required!" .Values.messageBroker.rabbitmq.port | quote }}
            - name: MessageBroker__RabbitMQ__Username
              value: {{ required "A valid messageBroker rabbitmq username is required!" .Values.messageBroker.rabbitmq.username }}
            - name: MessageBroker__RabbitMQ__Password
              value: {{ required "A valid messageBroker rabbitmq password is required!" .Values.messageBroker.rabbitmq.password }}
          {{- else if eq .Values.messageBroker.type "rabbitmqOperator" }}
            - name: MessageBroker__Type
              value: RabbitMq
            - name: MessageBroker__RabbitMQ__Host
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rabbitmq-default-user
                  key: host
            - name: MessageBroker__RabbitMQ__Port
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rabbitmq-default-user
                  key: port
            - name: MessageBroker__RabbitMQ__Username
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rabbitmq-default-user
                  key: username
            - name: MessageBroker__RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rabbitmq-default-user
                  key: password
          {{- else}}
            {{- fail "messageBroker type must be one of (inMemory | rabbitmq | rabbitmqOperator)" }}
          {{- end }}
            - name: Retry__DefaultFirstLevelRetryCount
              value: {{ .Values.messageBroker.retry.defaultFirstLevelRetryCount | quote }}
            - name: Retry__RegistryTransactionStillProcessingRetryCount
              value: {{ .Values.messageBroker.retry.registryTransactionStillProcessingRetryCount | quote }}
            - name: Retry__RegistryTransactionStillProcessingInitialIntervalSeconds
              value: {{ .Values.messageBroker.retry.registryTransactionStillProcessingInitialIntervalSeconds | quote }}
            - name: Retry__RegistryTransactionStillProcessingIntervalIncrementSeconds
              value: {{ .Values.messageBroker.retry.registryTransactionStillProcessingIntervalIncrementSeconds | quote }}

          {{- range $i, $registry := .Values.registries }}
            - name: Registries__{{ $i }}__name
              value: {{ $registry.name }}
            - name: Registries__{{ $i }}__address
              value: {{ $registry.address }}
          {{- end }}

          {{- range .Values.issuerPrivateKeyPems }}
            - name: IssuerPrivateKeyPems__{{ .gridArea }}
              value: {{ .key }}
          {{- end }}

            # OpenTelemetry Collector Configuration
            - name: Otlp__Enabled
              value: {{ .Values.otlp.enabled | quote }}
            - name: Otlp__Endpoint
              value: {{ .Values.otlp.endpoint }}
