---
apiVersion: batch/v1
kind: Job
metadata:
  name: po-stamp-migrate-job-{{ .Values.image.tag | default .Chart.AppVersion | replace "." "-" }}
  namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: 0
  parallelism: 1
  completions: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: po-stamp-migrate-job
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          securityContext: {{ toYaml .Values.job.securityContext | nindent 12 }}      
          args:
            - "--migrate"
          env:
            {{- include "common.database.config" $ | nindent 12 }}
